services:
  mongodb:
    image: mongo:7
    container_name: mern-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - mern-network

  api:
    build:
      context: ./mern-ecommerce-api
      dockerfile: Dockerfile
    container_name: mern-api
    restart: unless-stopped
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: development
      DATABASE_URI: mongodb://admin:password123@mongodb:27017/ecommerce?authSource=admin
      ACCESS_TOKEN_SECRET: your-access-token-secret-key-here
      REFRESH_TOKEN_SECRET: your-refresh-token-secret-key-here
    depends_on:
      - mongodb
    networks:
      - mern-network
    volumes:
      - ./mern-ecommerce-api:/app
      - /app/node_modules

  frontend:
    build:
      context: ./mern-ecommerce
      dockerfile: Dockerfile
    container_name: mern-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3500
    depends_on:
      - api
    networks:
      - mern-network
    volumes:
      - ./mern-ecommerce:/app
      - /app/node_modules

volumes:
  mongodb_data:


networks:
  mern-network:
    driver: bridge
